  - name: community.zabbix
    version: 3.2.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
  - name: ansible.netcommon
    version: 6.1.3
  - name: community.docker
    version: 3.13.1
  - name: ansible.windows
    version: 2.5.0
  - name: community.windows
    version: 2.3.0
