---
- name: Installing Ansible AWX
  hosts: localhost
  become: true
  tasks:
    - name: Install several packages
      apt:
        name:
          - netaddr
          - python3-virtualenv
          - python3-pip
        state: present
