---
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Transfer the script
       copy: src=install_zabbix.sh dest=/tmp mode=0777

     - name: Execute the script
       script: /tmp/install_zabbix.sh
