- hosts: all
#  become: true
  tasks:
    - name: Install local pip3
      apt:
        name: python3-pip
        state: present
      register: zabbix_python_pip3_package_installed
      until: zabbix_python_pip3_package_installed is succeeded
      delegate_to: localhost
      run_once: true
      tags: install_pip3
    - name: Install local netaddr
      apt:
        name: python3-netaddr
        state: present
      register: zabbix_python_netaddr_package_installed
      until: zabbix_python_netaddr_package_installed is succeeded
      delegate_to: localhost
      run_once: true
      tags: install_netaddr
    - name: Install agent
      include_role:
        name: community.zabbix.zabbix_agent
      vars:
        zabbix_agent2: true
        zabbix_agent_server: zabbix.silasveta.local
        zabbix_agent_serveractive: zabbix.silasveta.local
        zabbix_agent2_allow_key: ["system.run[*]"]
        zabbix_agent2_hostmetadataitem: system.uname
      tags:
        - install_agent
