- hosts: all
  tasks:
    - name: Install agent
      include_role:
        name:  community.zabbix.zabbix_agent # устанавливает готовую роль на хостах
      tags:
        - install # для удобства можно использовать тэги
      tags:
        - install # using tags for convenience     
    - name: Create a new host or update an existing host's info # task that registers agent in zabbix server
      local_action:
        module: community.zabbix.zabbix_host # using ansible module
        server_url: http://zbx.silasveta.local
        login_user: Admin
        login_password: zabbix
        host_name: "{{ item }}"  # hostname from ansible inventory
        visible_name: "{{ hostvars[item].zabbix_visible_name | default(item) }}" # a variable from inventory with host visible name defaults to hostname
        description: "Linux server" # takes description from inventory and adds OS distribution and version from ansible system variables
        host_groups: "Linux servers" # a variable from inventory with zabbix host group
        link_templates: "Linux by Zabbix agent"  # a variable from inventory with zabbix templates
        status: enable # a variable from inventory which defines that host is Enabled or Disabled
        state: present # tells ansible that host should be present, to delete host from zabbix server use absent
        inventory_mode: disabled # don’t use inventory mode
        interfaces: # interfaces to access a data, can be multiple values
          - type: agent # a variable from inventory with interface type, could be SNMP, Agent, JMX, IPMI
            main: 1 # tells zabbix that interfaces is main
            useip: 1 # tells whether to use ip or dns access to host
            ip: "" # if useip is chosen takes ip from inventory file
            dns: "{{ item }}" # if useip: 0 takes hostname from inventory
            port: 10050 # defines port
      loop: "{{ groups['all'] }}" # loop that iterates over all hosts in inventory
      run_once: true # loop will run on every host in inventory, so we tell ansible to run once
      tags:
        - add-host #  adding tags for convenience
